/* Generated by cbindgen. Do not edit. */

#ifndef SHELLAC_H
#define SHELLAC_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Apply an op batch to `path`. See module-level docs for the full contract.
 *
 * # Safety
 * `path` and `ops_json` must each be either NULL or a valid NUL-terminated
 * C string. The returned pointer, if non-NULL, must be freed with
 * [`shellac_free_string`].
 */
char *shellac_apply_ops(const char *path, const char *ops_json);

/**
 * Attempt to parse the PDF at `path` (filtered load).
 *
 * Return codes:
 * * 0 — OK, the PDF parsed successfully and is not encrypted
 * * 1 — parse_failed (malformed PDF or lopdf parse error)
 * * 2 — io_failed (read error, e.g. file not found or permission denied)
 * * 3 — invalid_arg (NULL pointer or non-UTF-8 path)
 * * 4 — panic (a Rust panic was caught at the FFI boundary)
 * * 5 — password_required (encrypted; the empty user password did not
 *   authenticate — a real user password is required to read the file)
 * * 6 — encrypted (encrypted; empty user password authenticated so lopdf
 *   was able to decrypt the objects, and an incremental save can
 *   re-encrypt what it appends under the retained key)
 * * 7 — annotations_restricted (encrypted; empty user password
 *   authenticated, but `/P` (permissions integer) has the `ANNOTABLE` bit
 *   clear so adding annotations is disallowed by the document producer.
 *   Reported separately so a caller can refuse the annotate operation up
 *   front rather than let the user think a save succeeded)
 *
 * # Encryption detection
 *
 * After a successful load, lopdf leaves the document in one of two states:
 *
 * * `was_encrypted() == true`: the PDF was encrypted, and lopdf successfully
 *   authenticated with the empty user password. Decrypted objects live in
 *   `document.objects`; the `/Encrypt` reference was removed from the
 *   trailer. `is_encrypted()` returns false in this state.
 * * `is_encrypted() == true`: the PDF was encrypted and the empty user
 *   password did NOT authenticate. lopdf preserved the `/Encrypt` trailer
 *   entry so callers can inspect it, but `document.objects` was NOT
 *   decrypted (a load with a password would be required for real use).
 *
 * Only the first state can produce a safe incremental update: lopdf keeps
 * the encryption state it authenticated with, so newly-written objects are
 * re-encrypted under the same key. In the second state there is no key to
 * encrypt under, and an increment would leave the trailer's `/Encrypt`
 * pointing at cleartext bytes — hence the separate return code.
 *
 * # Annotation permissions
 *
 * When `was_encrypted() == true`, `document.encryption_state.permissions()`
 * exposes the `/P` bitfield in its parsed form. We check
 * `Permissions::ANNOTABLE` (bit 6 of `/P`) and demote code `6` to `7` when
 * it is clear, so a caller can distinguish "encrypted but writable" from
 * "encrypted AND the producer disallows annotations".
 *
 * # Safety
 * `path` must be NULL or a valid NUL-terminated C string.
 */
int32_t shellac_can_open(const char *path);

/**
 * Free a string previously returned from [`shellac_apply_ops`]. Safe to
 * call with NULL (no-op).
 *
 * # Safety
 * `ptr` must either be NULL or a pointer previously returned by
 * [`shellac_apply_ops`], and must not be freed twice.
 */
void shellac_free_string(char *ptr);

#endif  /* SHELLAC_H */
